// Kana Dojo data: kana, kanji, sentences and vocabulary.
// Edit entries here; app.js reads these globals.

// ═══════════════════════════════════════
//  DATA — Hiragana & Katakana
// ═══════════════════════════════════════
const H = [
  {k:'あ',r:'a'},{k:'い',r:'i'},{k:'う',r:'u'},{k:'え',r:'e'},{k:'お',r:'o'},
  {k:'か',r:'ka'},{k:'き',r:'ki'},{k:'く',r:'ku'},{k:'け',r:'ke'},{k:'こ',r:'ko'},
  {k:'さ',r:'sa'},{k:'し',r:'shi'},{k:'す',r:'su'},{k:'せ',r:'se'},{k:'そ',r:'so'},
  {k:'た',r:'ta'},{k:'ち',r:'chi'},{k:'つ',r:'tsu'},{k:'て',r:'te'},{k:'と',r:'to'},
  {k:'な',r:'na'},{k:'に',r:'ni'},{k:'ぬ',r:'nu'},{k:'ね',r:'ne'},{k:'の',r:'no'},
  {k:'は',r:'ha'},{k:'ひ',r:'hi'},{k:'ふ',r:'fu'},{k:'へ',r:'he'},{k:'ほ',r:'ho'},
  {k:'ま',r:'ma'},{k:'み',r:'mi'},{k:'む',r:'mu'},{k:'め',r:'me'},{k:'も',r:'mo'},
  {k:'や',r:'ya'},{k:'ゆ',r:'yu'},{k:'よ',r:'yo'},
  {k:'ら',r:'ra'},{k:'り',r:'ri'},{k:'る',r:'ru'},{k:'れ',r:'re'},{k:'ろ',r:'ro'},
  {k:'わ',r:'wa'},{k:'を',r:'wo'},{k:'ん',r:'n'},
  {k:'が',r:'ga'},{k:'ぎ',r:'gi'},{k:'ぐ',r:'gu'},{k:'げ',r:'ge'},{k:'ご',r:'go'},
  {k:'ざ',r:'za'},{k:'じ',r:'ji'},{k:'ず',r:'zu'},{k:'ぜ',r:'ze'},{k:'ぞ',r:'zo'},
  {k:'だ',r:'da'},{k:'ぢ',r:'di'},{k:'づ',r:'du'},{k:'で',r:'de'},{k:'ど',r:'do'},
  {k:'ば',r:'ba'},{k:'び',r:'bi'},{k:'ぶ',r:'bu'},{k:'べ',r:'be'},{k:'ぼ',r:'bo'},
  {k:'ぱ',r:'pa'},{k:'ぴ',r:'pi'},{k:'ぷ',r:'pu'},{k:'ぺ',r:'pe'},{k:'ぽ',r:'po'},
  {k:'きゃ',r:'kya'},{k:'きゅ',r:'kyu'},{k:'きょ',r:'kyo'},
  {k:'しゃ',r:'sha'},{k:'しゅ',r:'shu'},{k:'しょ',r:'sho'},
  {k:'ちゃ',r:'cha'},{k:'ちゅ',r:'chu'},{k:'ちょ',r:'cho'},
  {k:'にゃ',r:'nya'},{k:'にゅ',r:'nyu'},{k:'にょ',r:'nyo'},
  {k:'ひゃ',r:'hya'},{k:'ひゅ',r:'hyu'},{k:'ひょ',r:'hyo'},
  {k:'みゃ',r:'mya'},{k:'みゅ',r:'myu'},{k:'みょ',r:'myo'},
  {k:'りゃ',r:'rya'},{k:'りゅ',r:'ryu'},{k:'りょ',r:'ryo'},
  {k:'ぎゃ',r:'gya'},{k:'ぎゅ',r:'gyu'},{k:'ぎょ',r:'gyo'},
  {k:'じゃ',r:'ja'},{k:'じゅ',r:'ju'},{k:'じょ',r:'jo'},
  {k:'びゃ',r:'bya'},{k:'びゅ',r:'byu'},{k:'びょ',r:'byo'},
  {k:'ぴゃ',r:'pya'},{k:'ぴゅ',r:'pyu'},{k:'ぴょ',r:'pyo'},
];
const KT = [
  {k:'ア',r:'a'},{k:'イ',r:'i'},{k:'ウ',r:'u'},{k:'エ',r:'e'},{k:'オ',r:'o'},
  {k:'カ',r:'ka'},{k:'キ',r:'ki'},{k:'ク',r:'ku'},{k:'ケ',r:'ke'},{k:'コ',r:'ko'},
  {k:'サ',r:'sa'},{k:'シ',r:'shi'},{k:'ス',r:'su'},{k:'セ',r:'se'},{k:'ソ',r:'so'},
  {k:'タ',r:'ta'},{k:'チ',r:'chi'},{k:'ツ',r:'tsu'},{k:'テ',r:'te'},{k:'ト',r:'to'},
  {k:'ナ',r:'na'},{k:'ニ',r:'ni'},{k:'ヌ',r:'nu'},{k:'ネ',r:'ne'},{k:'ノ',r:'no'},
  {k:'ハ',r:'ha'},{k:'ヒ',r:'hi'},{k:'フ',r:'fu'},{k:'ヘ',r:'he'},{k:'ホ',r:'ho'},
  {k:'マ',r:'ma'},{k:'ミ',r:'mi'},{k:'ム',r:'mu'},{k:'メ',r:'me'},{k:'モ',r:'mo'},
  {k:'ヤ',r:'ya'},{k:'ユ',r:'yu'},{k:'ヨ',r:'yo'},
  {k:'ラ',r:'ra'},{k:'リ',r:'ri'},{k:'ル',r:'ru'},{k:'レ',r:'re'},{k:'ロ',r:'ro'},
  {k:'ワ',r:'wa'},{k:'ヲ',r:'wo'},{k:'ン',r:'n'},
  {k:'ガ',r:'ga'},{k:'ギ',r:'gi'},{k:'グ',r:'gu'},{k:'ゲ',r:'ge'},{k:'ゴ',r:'go'},
  {k:'ザ',r:'za'},{k:'ジ',r:'ji'},{k:'ズ',r:'zu'},{k:'ゼ',r:'ze'},{k:'ゾ',r:'zo'},
  {k:'ダ',r:'da'},{k:'ヂ',r:'di'},{k:'ヅ',r:'du'},{k:'デ',r:'de'},{k:'ド',r:'do'},
  {k:'バ',r:'ba'},{k:'ビ',r:'bi'},{k:'ブ',r:'bu'},{k:'ベ',r:'be'},{k:'ボ',r:'bo'},
  {k:'パ',r:'pa'},{k:'ピ',r:'pi'},{k:'プ',r:'pu'},{k:'ペ',r:'pe'},{k:'ポ',r:'po'},
  {k:'キャ',r:'kya'},{k:'キュ',r:'kyu'},{k:'キョ',r:'kyo'},
  {k:'シャ',r:'sha'},{k:'シュ',r:'shu'},{k:'ショ',r:'sho'},
  {k:'チャ',r:'cha'},{k:'チュ',r:'chu'},{k:'チョ',r:'cho'},
  {k:'ニャ',r:'nya'},{k:'ニュ',r:'nyu'},{k:'ニョ',r:'nyo'},
  {k:'ヒャ',r:'hya'},{k:'ヒュ',r:'hyu'},{k:'ヒョ',r:'hyo'},
  {k:'ミャ',r:'mya'},{k:'ミュ',r:'myu'},{k:'ミョ',r:'myo'},
  {k:'リャ',r:'rya'},{k:'リュ',r:'ryu'},{k:'リョ',r:'ryo'},
  {k:'ギャ',r:'gya'},{k:'ギュ',r:'gyu'},{k:'ギョ',r:'gyo'},
  {k:'ジャ',r:'ja'},{k:'ジュ',r:'ju'},{k:'ジョ',r:'jo'},
  {k:'ビャ',r:'bya'},{k:'ビュ',r:'byu'},{k:'ビョ',r:'byo'},
  {k:'ピャ',r:'pya'},{k:'ピュ',r:'pyu'},{k:'ピョ',r:'pyo'},
];

// ═══════════════════════════════════════
//  DATA — 200 Kanji
//  fields: k=char, h=hiragana, t=katakana, e=english, c=category, rad=radical hint
// ═══════════════════════════════════════
const KANJI = [
  // Numbers
  {k:'一',h:'いち',t:'イチ',e:'one',c:'Numbers',rad:'一 (one stroke)'},
  {k:'二',h:'に',t:'ニ',e:'two',c:'Numbers',rad:'二 (two strokes)'},
  {k:'三',h:'さん',t:'サン',e:'three',c:'Numbers',rad:'三 (three strokes)'},
  {k:'四',h:'し・よん',t:'シ・ヨン',e:'four',c:'Numbers',rad:'囗 (enclosure)'},
  {k:'五',h:'ご',t:'ゴ',e:'five',c:'Numbers',rad:'二 (two)'},
  {k:'六',h:'ろく',t:'ロク',e:'six',c:'Numbers',rad:'八 (eight)'},
  {k:'七',h:'なな・しち',t:'ナナ・シチ',e:'seven',c:'Numbers',rad:'一 (one)'},
  {k:'八',h:'はち',t:'ハチ',e:'eight',c:'Numbers',rad:'八 (eight/split)'},
  {k:'九',h:'く・きゅう',t:'ク・キュウ',e:'nine',c:'Numbers',rad:'乙 (second)'},
  {k:'十',h:'じゅう',t:'ジュウ',e:'ten',c:'Numbers',rad:'十 (cross)'},
  {k:'百',h:'ひゃく',t:'ヒャク',e:'hundred',c:'Numbers',rad:'白 (white)'},
  {k:'千',h:'せん',t:'セン',e:'thousand',c:'Numbers',rad:'十 (ten)'},
  {k:'万',h:'まん',t:'マン',e:'ten thousand',c:'Numbers',rad:'一 (one)'},
  // Time
  {k:'年',h:'ねん・とし',t:'ネン',e:'year',c:'Time',rad:'干 (dry)'},
  {k:'月',h:'つき・がつ',t:'ゲツ・ガツ',e:'moon / month',c:'Time',rad:'月 (moon)'},
  {k:'日',h:'ひ・にち',t:'ニチ・ジツ',e:'sun / day',c:'Time',rad:'日 (sun)'},
  {k:'時',h:'じ・とき',t:'ジ',e:'time / hour',c:'Time',rad:'日 (sun) + 寸 (measure)'},
  {k:'今',h:'いま',t:'コン・キン',e:'now',c:'Time',rad:'人 (person) + 一'},
  {k:'週',h:'しゅう',t:'シュウ',e:'week',c:'Time',rad:'辶 (walk)'},
  {k:'昨',h:'さく',t:'サク',e:'yesterday / last',c:'Time',rad:'日 (sun) + 乍'},
  {k:'毎',h:'まい',t:'マイ',e:'every / each',c:'Time',rad:'毋 (mother)'},
  {k:'朝',h:'あさ',t:'チョウ',e:'morning',c:'Time',rad:'月 (moon) + 十'},
  {k:'夜',h:'よる',t:'ヤ',e:'night',c:'Time',rad:'夕 (evening) + 亦'},
  {k:'昼',h:'ひる',t:'チュウ',e:'noon / daytime',c:'Time',rad:'日 (sun) + 尺'},
  // People
  {k:'人',h:'ひと・じん',t:'ジン・ニン',e:'person',c:'People',rad:'人 (person)'},
  {k:'子',h:'こ',t:'シ・ス',e:'child',c:'People',rad:'子 (child)'},
  {k:'女',h:'おんな',t:'ジョ・ニョ',e:'woman',c:'People',rad:'女 (woman)'},
  {k:'男',h:'おとこ',t:'ダン・ナン',e:'man',c:'People',rad:'田 (rice field) + 力 (power)'},
  {k:'父',h:'ちち',t:'フ',e:'father',c:'People',rad:'父 (father/strike)'},
  {k:'母',h:'はは',t:'ボ',e:'mother',c:'People',rad:'母 (nurture)'},
  {k:'友',h:'とも',t:'ユウ',e:'friend',c:'People',rad:'又 (right hand)'},
  {k:'先',h:'せん・さき',t:'セン',e:'previous / ahead',c:'People',rad:'儿 (legs) + 土'},
  {k:'生',h:'い・う・なま',t:'セイ・ショウ',e:'life / birth / raw',c:'People',rad:'生 (sprout)'},
  {k:'名',h:'な・めい',t:'メイ・ミョウ',e:'name',c:'People',rad:'夕 (evening) + 口 (mouth)'},
  // Nature
  {k:'山',h:'やま',t:'サン',e:'mountain',c:'Nature',rad:'山 (mountain)'},
  {k:'川',h:'かわ',t:'セン',e:'river',c:'Nature',rad:'川 (river)'},
  {k:'水',h:'みず',t:'スイ',e:'water',c:'Nature',rad:'水 (water)'},
  {k:'火',h:'ひ',t:'カ',e:'fire',c:'Nature',rad:'火 (fire)'},
  {k:'木',h:'き',t:'モク・ボク',e:'tree / wood',c:'Nature',rad:'木 (tree)'},
  {k:'花',h:'はな',t:'カ',e:'flower',c:'Nature',rad:'艹 (grass) + 化'},
  {k:'空',h:'そら',t:'クウ',e:'sky / empty',c:'Nature',rad:'穴 (hole/cave)'},
  {k:'海',h:'うみ',t:'カイ',e:'sea / ocean',c:'Nature',rad:'氵(water) + 毎'},
  {k:'雨',h:'あめ',t:'ウ',e:'rain',c:'Nature',rad:'雨 (rain)'},
  {k:'石',h:'いし',t:'セキ・シャク',e:'stone / rock',c:'Nature',rad:'石 (stone)'},
  {k:'土',h:'つち',t:'ド・ト',e:'earth / soil',c:'Nature',rad:'土 (earth)'},
  {k:'風',h:'かぜ',t:'フウ・フ',e:'wind',c:'Nature',rad:'風 (wind)'},
  {k:'雪',h:'ゆき',t:'セツ',e:'snow',c:'Nature',rad:'雨 (rain) + 彐'},
  {k:'森',h:'もり',t:'シン',e:'forest',c:'Nature',rad:'木×3 (three trees)'},
  {k:'林',h:'はやし',t:'リン',e:'grove / woods',c:'Nature',rad:'木×2 (two trees)'},
  // Body
  {k:'手',h:'て',t:'シュ',e:'hand',c:'Body',rad:'手 (hand)'},
  {k:'目',h:'め',t:'モク・ボク',e:'eye',c:'Body',rad:'目 (eye)'},
  {k:'口',h:'くち',t:'コウ・ク',e:'mouth',c:'Body',rad:'口 (mouth)'},
  {k:'耳',h:'みみ',t:'ジ',e:'ear',c:'Body',rad:'耳 (ear)'},
  {k:'足',h:'あし',t:'ソク',e:'foot / leg',c:'Body',rad:'足 (foot)'},
  {k:'頭',h:'あたま',t:'トウ・ズ',e:'head',c:'Body',rad:'頁 (page/head)'},
  {k:'心',h:'こころ',t:'シン',e:'heart / mind',c:'Body',rad:'心 (heart)'},
  {k:'体',h:'からだ',t:'タイ・テイ',e:'body',c:'Body',rad:'人 (person) + 本'},
  // Direction / Place
  {k:'上',h:'うえ・じょう',t:'ジョウ',e:'up / above',c:'Direction',rad:'一 + 丨 (above line)'},
  {k:'下',h:'した・か',t:'カ・ゲ',e:'down / below',c:'Direction',rad:'一 + 丨 (below line)'},
  {k:'中',h:'なか・ちゅう',t:'チュウ',e:'inside / middle',c:'Direction',rad:'丨 (vertical) in 口'},
  {k:'右',h:'みぎ',t:'ウ',e:'right',c:'Direction',rad:'又 (right hand) + 口'},
  {k:'左',h:'ひだり',t:'サ',e:'left',c:'Direction',rad:'工 + 又 (left hand)'},
  {k:'東',h:'ひがし',t:'トウ',e:'east',c:'Direction',rad:'木 (tree) + 日 (sun through tree)'},
  {k:'西',h:'にし',t:'セイ・サイ',e:'west',c:'Direction',rad:'西 (bird\'s nest)'},
  {k:'南',h:'みなみ',t:'ナン',e:'south',c:'Direction',rad:'十 + 冂 + 羊'},
  {k:'北',h:'きた',t:'ホク',e:'north',c:'Direction',rad:'匕 (two people back to back)'},
  {k:'外',h:'そと',t:'ガイ・ゲ',e:'outside',c:'Direction',rad:'夕 (evening) + 卜'},
  {k:'内',h:'うち',t:'ナイ・ダイ',e:'inside / home',c:'Direction',rad:'冂 (frame) + 人'},
  // Actions
  {k:'食',h:'た(べる)・しょく',t:'ショク',e:'eat / food',c:'Actions',rad:'食 (eat/rice)'},
  {k:'飲',h:'の(む)',t:'イン',e:'drink',c:'Actions',rad:'食 (eat) + 欠 (lack/open mouth)'},
  {k:'見',h:'み(る)',t:'ケン',e:'see / look',c:'Actions',rad:'目 (eye) + 儿 (legs)'},
  {k:'聞',h:'き(く)',t:'ブン・モン',e:'listen / ask',c:'Actions',rad:'耳 (ear) in 門 (gate)'},
  {k:'行',h:'い(く)',t:'コウ・ギョウ',e:'go',c:'Actions',rad:'行 (crossroads)'},
  {k:'来',h:'く(る)・き',t:'ライ',e:'come',c:'Actions',rad:'木 (tree) + 人×2'},
  {k:'書',h:'か(く)',t:'ショ',e:'write',c:'Actions',rad:'聿 (brush) + 日'},
  {k:'読',h:'よ(む)',t:'ドク・トク',e:'read',c:'Actions',rad:'言 (words) + 売'},
  {k:'話',h:'はな(す)',t:'ワ',e:'speak / story',c:'Actions',rad:'言 (words) + 舌 (tongue)'},
  {k:'学',h:'まな(ぶ)・がく',t:'ガク',e:'study / learn',c:'Actions',rad:'爻 (pattern) + 冖 + 子'},
  {k:'出',h:'で(る)・だ(す)',t:'シュツ・スイ',e:'exit / come out',c:'Actions',rad:'凵 (container) + 屮 (sprout)'},
  {k:'入',h:'い(る)・はい(る)',t:'ニュウ',e:'enter / put in',c:'Actions',rad:'入 (enter)'},
  {k:'買',h:'か(う)',t:'バイ',e:'buy',c:'Actions',rad:'罒 (net) + 貝 (shell/money)'},
  {k:'売',h:'う(る)',t:'バイ',e:'sell',c:'Actions',rad:'士 + 冖 + 儿'},
  {k:'帰',h:'かえ(る)',t:'キ',e:'return / go home',c:'Actions',rad:'刀 + 冖 + 彐 + 止'},
  {k:'起',h:'お(きる)',t:'キ',e:'wake up / rise',c:'Actions',rad:'走 (run) + 己'},
  {k:'寝',h:'ね(る)',t:'シン',e:'sleep / lie down',c:'Actions',rad:'宀 (roof) + 爿 (bed)'},
  {k:'待',h:'ま(つ)',t:'タイ',e:'wait',c:'Actions',rad:'彳 (step) + 寺'},
  // Adjectives
  {k:'大',h:'おお(きい)・だい',t:'ダイ・タイ',e:'big / large',c:'Adjectives',rad:'大 (big person)'},
  {k:'小',h:'ちい(さい)・しょう',t:'ショウ',e:'small',c:'Adjectives',rad:'小 (small/three drops)'},
  {k:'高',h:'たか(い)',t:'コウ',e:'high / tall / expensive',c:'Adjectives',rad:'亠 + 口 + 冂 (tall building)'},
  {k:'低',h:'ひく(い)',t:'テイ',e:'low / short',c:'Adjectives',rad:'人 (person) + 氏'},
  {k:'長',h:'なが(い)',t:'チョウ',e:'long',c:'Adjectives',rad:'長 (long hair)'},
  {k:'短',h:'みじか(い)',t:'タン',e:'short (length)',c:'Adjectives',rad:'矢 (arrow) + 豆 (bean)'},
  {k:'新',h:'あたら(しい)',t:'シン',e:'new',c:'Adjectives',rad:'立 + 木 + 斤 (axe)'},
  {k:'古',h:'ふる(い)',t:'コ',e:'old',c:'Adjectives',rad:'十 (ten) + 口 (mouth — ten mouths old)'},
  {k:'好',h:'す(き)・こう',t:'コウ',e:'like / fond of',c:'Adjectives',rad:'女 (woman) + 子 (child)'},
  {k:'悪',h:'わる(い)',t:'アク・オ',e:'bad / evil',c:'Adjectives',rad:'亜 + 心 (heart)'},
  {k:'白',h:'しろ',t:'ハク',e:'white',c:'Adjectives',rad:'白 (white/sun ray)'},
  {k:'黒',h:'くろ',t:'コク',e:'black',c:'Adjectives',rad:'黒 (soot/fire)'},
  {k:'赤',h:'あか',t:'セキ・シャク',e:'red',c:'Adjectives',rad:'赤 (red fire)'},
  {k:'青',h:'あお',t:'セイ・ショウ',e:'blue / green',c:'Adjectives',rad:'生 (life) + 丹 (colour)'},
  // Society / World
  {k:'国',h:'くに',t:'コク',e:'country / nation',c:'Society',rad:'囗 (border) + 玉 (jewel)'},
  {k:'語',h:'ご',t:'ゴ',e:'language',c:'Society',rad:'言 (words) + 吾'},
  {k:'本',h:'ほん',t:'ホン',e:'book / origin',c:'Society',rad:'木 (tree) + 一 (root mark)'},
  {k:'校',h:'こう',t:'コウ',e:'school',c:'Society',rad:'木 (tree) + 交 (mix/intersect)'},
  {k:'家',h:'いえ・うち',t:'カ・ケ',e:'house / family',c:'Society',rad:'宀 (roof) + 豕 (pig)'},
  {k:'町',h:'まち',t:'チョウ',e:'town / city block',c:'Society',rad:'田 (field) + 丁 (street)'},
  {k:'市',h:'し',t:'シ',e:'city / market',c:'Society',rad:'市 (market)'},
  {k:'電',h:'でん',t:'デン',e:'electricity / electric',c:'Society',rad:'雨 (rain) + 申 (lightning)'},
  {k:'車',h:'くるま',t:'シャ',e:'car / vehicle',c:'Society',rad:'車 (wheel/cart)'},
  {k:'道',h:'みち',t:'ドウ・トウ',e:'road / way',c:'Society',rad:'辶 (walk) + 首 (head/neck)'},
  {k:'店',h:'みせ',t:'テン',e:'shop / store',c:'Society',rad:'广 (building) + 占 (occupy)'},
  {k:'駅',h:'えき',t:'エキ',e:'train station',c:'Society',rad:'馬 (horse) + 尺'},
  {k:'銀',h:'ぎん',t:'ギン',e:'silver / bank',c:'Society',rad:'金 (metal) + 艮'},
  {k:'金',h:'きん・かね',t:'キン・コン',e:'gold / money / metal',c:'Society',rad:'金 (metal/earth)'},
  {k:'会',h:'かい・あ(う)',t:'カイ・エ',e:'meet / association',c:'Society',rad:'人 + 云'},
  {k:'社',h:'しゃ',t:'シャ',e:'company / shrine',c:'Society',rad:'示 (spirit) + 土 (earth)'},
  // Food & Daily Life
  {k:'魚',h:'さかな',t:'ギョ',e:'fish',c:'Daily Life',rad:'魚 (fish)'},
  {k:'肉',h:'にく',t:'ニク',e:'meat / flesh',c:'Daily Life',rad:'肉 (flesh)'},
  {k:'米',h:'こめ',t:'マイ・ベイ',e:'rice (uncooked)',c:'Daily Life',rad:'米 (rice grains)'},
  {k:'茶',h:'ちゃ',t:'チャ・サ',e:'tea',c:'Daily Life',rad:'艹 (plant) + 人 + 木 (tree)'},
  {k:'服',h:'ふく',t:'フク',e:'clothes / garment',c:'Daily Life',rad:'月 + 卩 (seal) + 又 (hand)'},
  {k:'門',h:'かど',t:'モン',e:'gate',c:'Daily Life',rad:'門 (gate)'},
  {k:'窓',h:'まど',t:'ソウ',e:'window',c:'Daily Life',rad:'穴 (hole) + 囱'},
  {k:'色',h:'いろ',t:'ショク・シキ',e:'colour',c:'Daily Life',rad:'色 (colour/desire)'},
  {k:'音',h:'おと・ね',t:'オン・イン',e:'sound / music',c:'Daily Life',rad:'立 (stand) + 日 (sun)'},
  {k:'力',h:'ちから',t:'リョク・リキ',e:'strength / power',c:'Daily Life',rad:'力 (muscle)'},
  {k:'気',h:'き',t:'キ・ケ',e:'spirit / feeling / air',c:'Daily Life',rad:'气 (steam) + 米 (rice)'},
  {k:'明',h:'あか(るい)・めい',t:'メイ・ミョウ',e:'bright / clear',c:'Daily Life',rad:'日 (sun) + 月 (moon)'},

  // ════════════════════════════════════════
  //  GAME / VISUAL NOVEL KANJI
  // ════════════════════════════════════════

  // ── Combat & Skills ──
  {k:'戦',h:'たたか(う)・せん',t:'セン',e:'battle / war / fight',c:'Combat',rad:'単 (single) + 戈 (weapon)'},
  {k:'攻',h:'せ(める)',t:'コウ',e:'attack / assault',c:'Combat',rad:'工 (work) + 攴 (strike)'},
  {k:'守',h:'まも(る)',t:'シュ',e:'defend / protect / guard',c:'Combat',rad:'宀 (roof) + 寸 (measure)'},
  {k:'勝',h:'か(つ)',t:'ショウ',e:'win / victory',c:'Combat',rad:'月 (flesh) + 力 (power)'},
  {k:'負',h:'ま(ける)',t:'フ',e:'lose / defeat',c:'Combat',rad:'刀 (blade) + 貝 (shell)'},
  {k:'技',h:'わざ',t:'ギ',e:'skill / technique',c:'Combat',rad:'手 (hand) + 支 (branch)'},
  {k:'術',h:'じゅつ',t:'ジュツ',e:'art / technique / magic',c:'Combat',rad:'行 (go) + 朮'},
  {k:'剣',h:'けん',t:'ケン',e:'sword',c:'Combat',rad:'刂 (knife) + 僉'},
  {k:'矢',h:'や',t:'シ',e:'arrow',c:'Combat',rad:'矢 (arrow)'},
  {k:'盾',h:'たて',t:'ジュン',e:'shield',c:'Combat',rad:'十 + 目 (eye)'},

  // ── Magic & Spirits ──
  {k:'魔',h:'ま',t:'マ',e:'magic / demon / evil',c:'Magic',rad:'麻 (hemp) + 鬼 (demon)'},
  {k:'法',h:'ほう',t:'ホウ',e:'law / method / spell',c:'Magic',rad:'氵(water) + 去 (go)'},
  {k:'霊',h:'たま・れい',t:'レイ',e:'spirit / ghost / soul',c:'Magic',rad:'雨 (rain) + 彐×3'},
  {k:'呪',h:'のろ(い)',t:'ジュ',e:'curse / spell / incantation',c:'Magic',rad:'口 (mouth) + 兄'},
  {k:'神',h:'かみ',t:'シン・ジン',e:'god / divine / spirit',c:'Magic',rad:'示 (spirit) + 申 (lightning)'},
  {k:'幻',h:'まぼろし',t:'ゲン',e:'illusion / phantom',c:'Magic',rad:'幺 (thread) + 亅 (hook)'},
  {k:'封',h:'ふう・ふ(じる)',t:'フウ',e:'seal / to seal',c:'Magic',rad:'土 (earth) + 寸 (measure)'},
  {k:'召',h:'め(す)',t:'ショウ',e:'summon / call',c:'Magic',rad:'刀 (blade) + 口 (mouth)'},
  {k:'祈',h:'いの(る)',t:'キ',e:'pray / wish',c:'Magic',rad:'示 (spirit) + 斤 (axe)'},
  {k:'祝',h:'いわ(う)',t:'シュク・シュウ',e:'celebrate / blessing',c:'Magic',rad:'示 (spirit) + 兄'},

  // ── Emotion & Drama ──
  {k:'愛',h:'あい',t:'アイ',e:'love',c:'Emotion',rad:'爪 + 冖 + 心 + 夂'},
  {k:'怒',h:'おこ(る)',t:'ド・ヌ',e:'anger / rage',c:'Emotion',rad:'女 (woman) + 又 + 心'},
  {k:'悲',h:'かな(しい)',t:'ヒ',e:'sad / grief',c:'Emotion',rad:'非 (oppose) + 心 (heart)'},
  {k:'喜',h:'よろこ(ぶ)',t:'キ',e:'joy / delight',c:'Emotion',rad:'壴 (drum) + 口 (mouth)'},
  {k:'恐',h:'おそ(れる)',t:'キョウ',e:'fear / dread',c:'Emotion',rad:'巩 + 心 (heart)'},
  {k:'恋',h:'こい',t:'レン',e:'love / longing / romance',c:'Emotion',rad:'亦 + 心 (heart)'},
  {k:'涙',h:'なみだ',t:'ルイ',e:'tears',c:'Emotion',rad:'氵(water) + 戻'},
  {k:'笑',h:'わら(う)',t:'ショウ',e:'laugh / smile',c:'Emotion',rad:'竹 (bamboo) + 夭'},
  {k:'夢',h:'ゆめ',t:'ム',e:'dream',c:'Emotion',rad:'艹 + 罒 + 冖 + 夕 (evening)'},
  {k:'希',h:'まれ',t:'キ',e:'hope / rare / wish',c:'Emotion',rad:'巾 (cloth) + 乂'},

  // ── Story & Narrative ──
  {k:'王',h:'おう',t:'オウ',e:'king / ruler',c:'Story',rad:'王 (king / jewel)'},
  {k:'帝',h:'みかど',t:'テイ',e:'emperor',c:'Story',rad:'立 (stand) + 巾 (cloth)'},
  {k:'姫',h:'ひめ',t:'キ',e:'princess',c:'Story',rad:'女 (woman) + 臣 (retainer)'},
  {k:'勇',h:'いさ(む)',t:'ユウ',e:'brave / courage',c:'Story',rad:'甬 + 力 (power)'},
  {k:'英',h:'えい',t:'エイ',e:'outstanding / English',c:'Story',rad:'艹 (plant) + 央 (center)'},
  {k:'運',h:'うん',t:'ウン',e:'luck / fate / transport',c:'Story',rad:'辶 (walk) + 軍 (army)'},
  {k:'命',h:'いのち',t:'メイ・ミョウ',e:'life / fate / order',c:'Story',rad:'口 (mouth) + 令 (order)'},
  {k:'旅',h:'たび',t:'リョ',e:'journey / travel',c:'Story',rad:'方 (direction) + 人'},
  {k:'仲',h:'なか',t:'チュウ',e:'relationship / fellow',c:'Story',rad:'人 (person) + 中 (middle)'},
  {k:'絆',h:'きずな',t:'ハン',e:'bond / emotional tie',c:'Story',rad:'糸 (thread) + 半 (half)'},

  // ── World & Settings ──
  {k:'城',h:'しろ・じょう',t:'ジョウ',e:'castle',c:'World',rad:'土 (earth) + 成 (become)'},
  {k:'塔',h:'とう',t:'トウ',e:'tower',c:'World',rad:'土 (earth) + 荅'},
  {k:'洞',h:'ほら',t:'ドウ',e:'cave / cavern',c:'World',rad:'氵(water) + 同 (same)'},
  {k:'島',h:'しま',t:'トウ',e:'island',c:'World',rad:'山 (mountain) + 鳥 (bird)'},
  {k:'野',h:'の',t:'ヤ',e:'field / wilderness',c:'World',rad:'里 (village) + 予'},
  {k:'港',h:'みなと',t:'コウ',e:'harbour / port',c:'World',rad:'氵(water) + 巷'},
  {k:'橋',h:'はし',t:'キョウ',e:'bridge',c:'World',rad:'木 (tree) + 喬'},
  {k:'宮',h:'みや',t:'キュウ・グウ',e:'palace / shrine',c:'World',rad:'宀 (roof) + 呂'},
  {k:'廃',h:'すた(れる)',t:'ハイ',e:'abolish / abandon',c:'World',rad:'广 (building) + 発'},
  {k:'扉',h:'とびら',t:'ヒ',e:'door / title page',c:'World',rad:'戸 (door) + 非 (oppose)'},

  // ── Game Systems ──
  {k:'強',h:'つよ(い)',t:'キョウ・ゴウ',e:'strong / powerful',c:'Game Systems',rad:'弓 (bow) + 虫 (insect)'},
  {k:'弱',h:'よわ(い)',t:'ジャク',e:'weak',c:'Game Systems',rad:'弓 (bow) + 彡 (stripes)'},
  {k:'速',h:'はや(い)',t:'ソク',e:'fast / speed',c:'Game Systems',rad:'辶 (walk) + 束 (bundle)'},
  {k:'遅',h:'おそ(い)',t:'チ',e:'slow / late',c:'Game Systems',rad:'辶 (walk) + 犀'},
  {k:'増',h:'ふ(える)',t:'ゾウ',e:'increase / gain',c:'Game Systems',rad:'土 (earth) + 曽'},
  {k:'減',h:'へ(る)',t:'ゲン',e:'decrease / reduce',c:'Game Systems',rad:'氵(water) + 咸'},
  {k:'回',h:'まわ(る)',t:'カイ',e:'round / return / times',c:'Game Systems',rad:'囗 (enclosure) + 口'},
  {k:'復',h:'—',t:'フク',e:'recover / restore',c:'Game Systems',rad:'彳(step) + 复'},
  {k:'経',h:'へ(る)',t:'ケイ・キョウ',e:'pass / sutra / experience',c:'Game Systems',rad:'糸 (thread) + 巠'},
  {k:'験',h:'—',t:'ケン・ゲン',e:'experience / test / effect',c:'Game Systems',rad:'馬 (horse) + 僉'},

  // ── Darkness & Conflict ──
  {k:'闇',h:'やみ',t:'アン',e:'darkness',c:'Darkness',rad:'門 (gate) + 音 (sound)'},
  {k:'鬼',h:'おに',t:'キ',e:'demon / ogre',c:'Darkness',rad:'鬼 (demon head + legs)'},
  {k:'死',h:'し(ぬ)',t:'シ',e:'death / die',c:'Darkness',rad:'歹 (bone) + 匕 (spoon/death)'},
  {k:'血',h:'ち',t:'ケツ',e:'blood',c:'Darkness',rad:'血 (blood vessel)'},
  {k:'罪',h:'つみ',t:'ザイ',e:'sin / crime / guilt',c:'Darkness',rad:'罒 (net) + 非 (oppose)'},
  {k:'謀',h:'はか(る)',t:'ボウ・ム',e:'plot / scheme / conspiracy',c:'Darkness',rad:'言 (words) + 某'},
  {k:'怨',h:'うら(む)',t:'エン・オン',e:'grudge / resentment',c:'Darkness',rad:'夕 (evening) + 心 (heart)'},
  {k:'奪',h:'うば(う)',t:'ダツ',e:'snatch / steal / rob',c:'Darkness',rad:'隹 (bird) + 寸 + 大'},
  {k:'逃',h:'に(げる)',t:'トウ',e:'escape / flee',c:'Darkness',rad:'辶 (walk) + 兆'},
  {k:'滅',h:'ほろ(びる)',t:'メツ',e:'destroy / perish / annihilate',c:'Darkness',rad:'氵(water) + 烕'},
// ── Elements & Forces ──
  {k:'光',h:'ひかり',t:'コウ',e:'light / ray',c:'Elements',rad:'⺌ (small flame) + 儿 (legs)'},
  {k:'炎',h:'ほのお',t:'エン',e:'flame / blaze',c:'Elements',rad:'火×2 (two fires)'},
  {k:'氷',h:'こおり',t:'ヒョウ',e:'ice',c:'Elements',rad:'水 (water) + 冫 (ice)'},
  {k:'雷',h:'かみなり',t:'ライ',e:'thunder / lightning',c:'Elements',rad:'雨 (rain) + 田 (field)'},
  {k:'影',h:'かげ',t:'エイ',e:'shadow / silhouette',c:'Elements',rad:'景 (scenery) + 彡 (stripes)'},
  {k:'嵐',h:'あらし',t:'ラン',e:'storm / tempest',c:'Elements',rad:'山 (mountain) + 風 (wind)'},
  {k:'霧',h:'きり',t:'ム',e:'mist / fog',c:'Elements',rad:'雨 (rain) + 務 (duty)'},
  {k:'煙',h:'けむり',t:'エン',e:'smoke',c:'Elements',rad:'火 (fire) + 垔'},
  {k:'砂',h:'すな',t:'サ',e:'sand',c:'Elements',rad:'石 (stone) + 少 (few)'},
  {k:'岩',h:'いわ',t:'ガン',e:'rock / boulder',c:'Elements',rad:'山 (mountain) + 石 (stone)'},

  // ── Sacred & Forbidden ──
  {k:'聖',h:'ひじり',t:'セイ',e:'holy / sacred / saint',c:'Sacred',rad:'耳 (ear) + 呈 (present)'},
  {k:'邪',h:'よこしま',t:'ジャ',e:'evil / wicked / heretical',c:'Sacred',rad:'牙 (fang) + 阝 (mound)'},
  {k:'禁',h:'きん',t:'キン',e:'forbidden / prohibited',c:'Sacred',rad:'林 (grove) + 示 (spirit)'},
  {k:'禍',h:'わざわい',t:'カ',e:'calamity / curse / disaster',c:'Sacred',rad:'示 (spirit) + 咼'},
  {k:'竜',h:'りゅう・たつ',t:'リュウ',e:'dragon',c:'Sacred',rad:'竜 (dragon)'},
  {k:'獣',h:'けもの',t:'ジュウ',e:'beast / creature',c:'Sacred',rad:'単 + 犬 (dog)'},
  {k:'翼',h:'つばさ',t:'ヨク',e:'wing',c:'Sacred',rad:'羽 (feather) + 異 (different)'},
  {k:'縛',h:'しば(る)',t:'バク',e:'bind / restrain / shackle',c:'Sacred',rad:'糸 (thread) + 尃'},
  {k:'契',h:'ちぎ(る)',t:'ケイ',e:'pact / vow / contract',c:'Sacred',rad:'丰 (abundant) + 大 + 刀'},
  {k:'覚',h:'おぼ(える)・さ(める)',t:'カク',e:'awaken / recall / sense',c:'Sacred',rad:'爻 + 冖 + 見 (see)'},

  // ── Movement & Change ──
  {k:'走',h:'はし(る)',t:'ソウ',e:'run',c:'Movement',rad:'走 (running feet)'},
  {k:'飛',h:'と(ぶ)',t:'ヒ',e:'fly / jump / leap',c:'Movement',rad:'飛 (flying bird spread)'},
  {k:'動',h:'うご(く)',t:'ドウ',e:'move / motion',c:'Movement',rad:'重 (heavy) + 力 (power)'},
  {k:'止',h:'と(まる)',t:'シ',e:'stop / halt',c:'Movement',rad:'止 (footprint/stop)'},
  {k:'始',h:'はじ(まる)',t:'シ',e:'begin / start',c:'Movement',rad:'女 (woman) + 台 (platform)'},
  {k:'終',h:'お(わる)',t:'シュウ',e:'end / finish',c:'Movement',rad:'糸 (thread) + 冬 (winter)'},
  {k:'変',h:'か(わる)',t:'ヘン',e:'change / transform / strange',c:'Movement',rad:'亦 + 攵 (strike)'},
  {k:'転',h:'ころ(がる)',t:'テン',e:'turn / roll / change',c:'Movement',rad:'車 (wheel) + 専 (exclusive)'},
  {k:'解',h:'と(く)',t:'カイ',e:'release / solve / understand',c:'Movement',rad:'角 (horn) + 刀 + 牛 (cow)'},
  {k:'刻',h:'きざ(む)',t:'コク',e:'engrave / carve / moment',c:'Movement',rad:'亥 (boar) + 刀 (blade)'},

  // ── Mind & Will ──
  {k:'誠',h:'まこと',t:'セイ',e:'sincerity / honesty / truth',c:'Mind',rad:'言 (words) + 成 (become)'},
  {k:'信',h:'しん',t:'シン',e:'trust / faith / believe',c:'Mind',rad:'人 (person) + 言 (words)'},
  {k:'義',h:'ぎ',t:'ギ',e:'righteousness / duty / justice',c:'Mind',rad:'羊 (sheep) + 我 (I/self)'},
  {k:'恥',h:'は(じる)',t:'チ',e:'shame / disgrace',c:'Mind',rad:'耳 (ear) + 心 (heart)'},
  {k:'誇',h:'ほこ(る)',t:'コ',e:'pride / boast',c:'Mind',rad:'言 (words) + 夸'},
  {k:'憎',h:'にく(む)',t:'ゾウ',e:'hate / detest / loathe',c:'Mind',rad:'忄(heart) + 曾'},
  {k:'孤',h:'こ',t:'コ',e:'isolation / alone / orphan',c:'Mind',rad:'子 (child) + 瓜 (gourd)'},
  {k:'迷',h:'まよ(う)',t:'メイ',e:'lost / confused / wander',c:'Mind',rad:'辶 (walk) + 米 (rice)'},
  {k:'狂',h:'くる(う)',t:'キョウ',e:'crazy / mad / wild',c:'Mind',rad:'犬 (dog) + 王 (king)'},
  {k:'忘',h:'わす(れる)',t:'ボウ',e:'forget',c:'Mind',rad:'亡 (perish) + 心 (heart)'},

  // ── Power & Rule ──
  {k:'覇',h:'は',t:'ハ',e:'supremacy / domination / champion',c:'Power',rad:'西 (west) + 革 (leather) + 月'},
  {k:'権',h:'けん',t:'ケン',e:'right / authority / power',c:'Power',rad:'木 (tree) + 雚'},
  {k:'将',h:'しょう',t:'ショウ',e:'general / commander / leader',c:'Power',rad:'丬 + 夕 + 寸 (measure)'},
  {k:'士',h:'し',t:'シ',e:'warrior / samurai / gentleman',c:'Power',rad:'士 (scholar-warrior)'},
  {k:'兵',h:'つわもの・へい',t:'ヘイ',e:'soldier / weapon / warfare',c:'Power',rad:'斤 (axe) + 八 (eight)'},
  {k:'軍',h:'ぐん',t:'グン',e:'army / military forces',c:'Power',rad:'冖 (cover) + 車 (vehicle)'},
  {k:'陣',h:'じん',t:'ジン',e:'battle formation / camp',c:'Power',rad:'阝 (mound) + 車 (vehicle)'},
  {k:'旗',h:'はた',t:'キ',e:'flag / banner / standard',c:'Power',rad:'方 (direction) + 其 + 斤'},
  {k:'制',h:'せい',t:'セイ',e:'control / system / rule',c:'Power',rad:'𠂉 + 巾 + 刂 (knife)'},
  {k:'征',h:'せい',t:'セイ',e:'conquer / subjugate / march',c:'Power',rad:'彳 (step) + 正 (correct)'},
];


const SENTENCES = [
  {jp:'わたしは がくせい です。',r:'Watashi wa gakusei desu.',e:"I am a student.",v:'わたし (I) · がくせい (student) · です (am/is)'},
  {jp:'これは 本（ほん）です。',r:'Kore wa hon desu.',e:'This is a book.',v:'これ (this) · 本 (book)'},
  {jp:'きょうは いい 天気（てんき）ですね。',r:'Kyou wa ii tenki desu ne.',e:"The weather is nice today, isn't it?",v:'きょう (today) · いい (good) · 天気 (weather)'},
  {jp:'わたしは 水（みず）を 飲（の）みます。',r:'Watashi wa mizu wo nomimasu.',e:'I drink water.',v:'水 (water) · 飲みます (drink)'},
  {jp:'彼女（かのじょ）は 花（はな）が 好（す）きです。',r:'Kanojo wa hana ga suki desu.',e:'She likes flowers.',v:'彼女 (she) · 花 (flower) · 好き (like)'},
  {jp:'コーヒーをください。',r:'Koohii wo kudasai.',e:'Please give me a coffee.',v:'コーヒー (coffee — katakana loanword) · ください (please give)'},
  {jp:'東京（とうきょう）は 大（おお）きい 都市（とし）です。',r:'Toukyou wa ookii toshi desu.',e:'Tokyo is a big city.',v:'東京 (Tokyo) · 大きい (big) · 都市 (city)'},
  {jp:'わたしは 日本語（にほんご）を 勉強（べんきょう）しています。',r:'Watashi wa nihongo wo benkyou shite imasu.',e:'I am studying Japanese.',v:'日本語 (Japanese language) · 勉強 (study)'},
  {jp:'アイスクリームが 食（た）べたい！',r:'Aisu kuriimu ga tabetai!',e:'I want to eat ice cream!',v:'アイスクリーム (ice cream — katakana) · 食べたい (want to eat)'},
  {jp:'毎日（まいにち）本（ほん）を 読（よ）みます。',r:'Mainichi hon wo yomimasu.',e:'I read a book every day.',v:'毎日 (every day) · 本 (book) · 読みます (read)'},
  {jp:'山（やま）の 上（うえ）に 雪（ゆき）があります。',r:'Yama no ue ni yuki ga arimasu.',e:'There is snow on top of the mountain.',v:'山 (mountain) · 上 (above/top) · 雪 (snow)'},
  {jp:'友達（ともだち）と 映画（えいが）を 見（み）ました。',r:'Tomodachi to eiga wo mimashita.',e:'I watched a movie with a friend.',v:'友達 (friend) · 映画 (movie) · 見ました (watched)'},
  {jp:'お母さん（かあさん）は 料理（りょうり）が 上手（じょうず）です。',r:'Okaasan wa ryouri ga jouzu desu.',e:'Mom is good at cooking.',v:'お母さん (mom) · 料理 (cooking) · 上手 (skilled)'},
  {jp:'スーパーで 牛乳（ぎゅうにゅう）を 買（か）いました。',r:'Suupaa de gyuunyuu wo kaimashita.',e:'I bought milk at the supermarket.',v:'スーパー (supermarket — katakana) · 牛乳 (milk) · 買いました (bought)'},
  {jp:'電車（でんしゃ）で 駅（えき）まで 行（い）きます。',r:'Densha de eki made ikimasu.',e:'I go to the station by train.',v:'電車 (train) · 駅 (station) · 行きます (go)'},
  {jp:'この 道（みち）は 長（なが）いです。',r:'Kono michi wa nagai desu.',e:'This road is long.',v:'道 (road) · 長い (long)'},
  {jp:'時間（じかん）が ありませんから、 急（いそ）ぎます。',r:'Jikan ga arimasen kara, isogimasu.',e:'Because I don\'t have time, I will hurry.',v:'時間 (time) · ありません (do not have) · から (because) · 急ぎます (hurry)'},
  {jp:'昨日（きのう）は どこも 行（い）きませんでした。',r:'Kinou wa dokomo ikimasendeshita.',e:'I didn\'t go anywhere yesterday.',v:'昨日 (yesterday) · どこも (nowhere/anywhere with negative) · 行きませんでした (did not go)'},
  {jp:'窓（まど）を 開（あ）けても いいですか。',r:'Mado wo akete mo ii desu ka.',e:'May I open the window?',v:'窓 (window) · 開けてもいい (may I open — permission form)'},
  {jp:'デパートで 新（あたら）しい 靴（くつ）を 探（さが）しています。',r:'Depaato de atarashii kutsu wo sagashite imasu.',e:'I am looking for new shoes at the department store.',v:'デパート (department store) · 靴 (shoes) · 探しています (looking for)'},
  {jp:'日本語（にほんご）で 話（はな）してください。',r:'Nihongo de hanashite kudasai.',e:'Please speak in Japanese.',v:'日本語 (Japanese language) · 話してください (please speak)'},
  {jp:'部屋（へや）の 鍵（かぎ）を 忘（わす）れました！',r:'Heya no kagi wo wasuremashita!',e:'I forgot my room key!',v:'部屋 (room) · 鍵 (key) · 忘れました (forgot)'},
  {jp:'傘（かさ）を 持（も）っていますか。',r:'Kasa wo motte imasu ka.',e:'Do you have an umbrella?',v:'傘 (umbrella) · 持っています (to hold/possess)'},
  {jp:'日曜日（にちようび）は 公園（こうえん）を 散歩（さんぽ）します。',r:'Nichiyoubi wa kouen wo sanpo shimasu.',e:'On Sundays, I take a walk in the park.',v:'日曜日 (Sunday) · 公園 (park) · 散歩します (take a walk)'},
  {jp:'冷（つめ）たい お水（みず）を 一杯（いっぱい） お願（ねが）いします。',r:'Tsumetai omizu wo ippai onegai shimasu.',e:'A glass of cold water, please.',v:'冷たい (cold to touch) · 一杯 (one glass/cup) · お願いします (please)'},
  {jp:'この 料理（りょうり）は 少（すこ）し 辛（から）いです。',r:'Kono ryouri wa sukoshi karai desu.',e:'This dish is a little spicy.',v:'料理 (dish/cooking) · 少し (a little) · 辛い (spicy)'},
  {jp:'会社（かいしゃ）の 後（あと）で 病院（びょういん）へ 行（い）きます。',r:'Kaisha no ato de byouin e ikimasu.',e:'I am going to the hospital after work.',v:'会社 (company/work) · 後で (after) · 病院 (hospital)'},
  {jp:'財布（さいふ）の中に お金（かね）が いくら ありますか。',r:'Saifu no naka ni okane ga ikura arimasu ka.',e:'How much money is in the wallet?',v:'財布 (wallet) · 中 (inside) · お金 (money) · いくら (how much)'},
  {jp:'昨日（きのう） 撮（と）った 写真（しゃしん）を 見（み）せてください。',r:'Kinou totta shashin wo misete kudasai.',e:'Please show me the photo you took yesterday.',v:'撮った (took a photo) · 写真 (photo) · 見せてください (please show)'},
  {jp:'ホテルは 賑（にぎ）やかな 通（とお）りに あります。',r:'Hoteru wa nigiyaka na toori ni arimasu.',e:'The hotel is located on a lively street.',v:'ホテル (hotel) · 賑やか (lively/bustling) · 通り (street)'},
  {jp:'時計（とけい）を 直（なお）す ことが できますか。',r:'Tokei wo naosu koto ga dekimasu ka.',e:'Can you fix the clock?',v:'時計 (clock/watch) · 直す (to fix) · ことができます (can do)'},
];


// ═══════════════════════════════════════
//  VOCABULARY DATA — 160 words
// ═══════════════════════════════════════
const VOCAB = [
  // ── Greetings (10) ──
  {jp:'こんにちは',h:'こんにちは',t:'コンニチハ',r:'konnichiwa',e:'hello / good afternoon',c:'Greetings'},
  {jp:'おはよう',h:'おはよう',t:'オハヨウ',r:'ohayou',e:'good morning',c:'Greetings'},
  {jp:'こんばんは',h:'こんばんは',t:'コンバンハ',r:'konbanwa',e:'good evening',c:'Greetings'},
  {jp:'さようなら',h:'さようなら',t:'サヨウナラ',r:'sayounara',e:'goodbye',c:'Greetings'},
  {jp:'ありがとう',h:'ありがとう',t:'アリガトウ',r:'arigatou',e:'thank you',c:'Greetings'},
  {jp:'すみません',h:'すみません',t:'スミマセン',r:'sumimasen',e:'excuse me / sorry',c:'Greetings'},
  {jp:'はじめまして',h:'はじめまして',t:'ハジメマシテ',r:'hajimemashite',e:'nice to meet you',c:'Greetings'},
  {jp:'どうぞよろしく',h:'どうぞよろしく',t:'ドウゾヨロシク',r:'douzo yoroshiku',e:'pleased to meet you',c:'Greetings'},
  {jp:'いただきます',h:'いただきます',t:'イタダキマス',r:'itadakimasu',e:'let\'s eat (before meals)',c:'Greetings'},
  {jp:'ごちそうさま',h:'ごちそうさま',t:'ゴチソウサマ',r:'gochisousama',e:'thank you for the meal',c:'Greetings'},

  // ── Pronouns & People (10) ──
  {jp:'わたし',h:'わたし',t:'ワタシ',r:'watashi',e:'I / me',c:'Pronouns'},
  {jp:'あなた',h:'あなた',t:'アナタ',r:'anata',e:'you',c:'Pronouns'},
  {jp:'かれ',h:'かれ',t:'カレ',r:'kare',e:'he / him / boyfriend',c:'Pronouns'},
  {jp:'かのじょ',h:'かのじょ',t:'カノジョ',r:'kanojo',e:'she / her / girlfriend',c:'Pronouns'},
  {jp:'わたしたち',h:'わたしたち',t:'ワタシタチ',r:'watashitachi',e:'we / us',c:'Pronouns'},
  {jp:'みんな',h:'みんな',t:'ミンナ',r:'minna',e:'everyone',c:'Pronouns'},
  {jp:'ともだち',h:'ともだち',t:'トモダチ',r:'tomodachi',e:'friend',c:'Pronouns'},
  {jp:'せんせい',h:'せんせい',t:'センセイ',r:'sensei',e:'teacher / master',c:'Pronouns'},
  {jp:'がくせい',h:'がくせい',t:'ガクセイ',r:'gakusei',e:'student',c:'Pronouns'},
  {jp:'こども',h:'こども',t:'コドモ',r:'kodomo',e:'child / children',c:'Pronouns'},

  // ── Verbs I — Motion & Basics (10) ──
  {jp:'たべる',h:'たべる',t:'タベル',r:'taberu',e:'to eat',c:'Verbs I'},
  {jp:'のむ',h:'のむ',t:'ノム',r:'nomu',e:'to drink',c:'Verbs I'},
  {jp:'みる',h:'みる',t:'ミル',r:'miru',e:'to see / to watch',c:'Verbs I'},
  {jp:'きく',h:'きく',t:'キク',r:'kiku',e:'to listen / to hear',c:'Verbs I'},
  {jp:'いく',h:'いく',t:'イク',r:'iku',e:'to go',c:'Verbs I'},
  {jp:'くる',h:'くる',t:'クル',r:'kuru',e:'to come',c:'Verbs I'},
  {jp:'かえる',h:'かえる',t:'カエル',r:'kaeru',e:'to return / go home',c:'Verbs I'},
  {jp:'はなす',h:'はなす',t:'ハナス',r:'hanasu',e:'to speak / to talk',c:'Verbs I'},
  {jp:'よむ',h:'よむ',t:'ヨム',r:'yomu',e:'to read',c:'Verbs I'},
  {jp:'かく',h:'かく',t:'カク',r:'kaku',e:'to write',c:'Verbs I'},

  // ── Verbs II — Daily Actions (10) ──
  {jp:'おきる',h:'おきる',t:'オキル',r:'okiru',e:'to wake up',c:'Verbs II'},
  {jp:'ねる',h:'ねる',t:'ネル',r:'neru',e:'to sleep',c:'Verbs II'},
  {jp:'かう',h:'かう',t:'カウ',r:'kau',e:'to buy',c:'Verbs II'},
  {jp:'まつ',h:'まつ',t:'マツ',r:'matsu',e:'to wait',c:'Verbs II'},
  {jp:'わかる',h:'わかる',t:'ワカル',r:'wakaru',e:'to understand',c:'Verbs II'},
  {jp:'おもう',h:'おもう',t:'オモウ',r:'omou',e:'to think / to feel',c:'Verbs II'},
  {jp:'つかう',h:'つかう',t:'ツカウ',r:'tsukau',e:'to use',c:'Verbs II'},
  {jp:'おしえる',h:'おしえる',t:'オシエル',r:'oshieru',e:'to teach / to tell',c:'Verbs II'},
  {jp:'あう',h:'あう',t:'アウ',r:'au',e:'to meet',c:'Verbs II'},
  {jp:'はいる',h:'はいる',t:'ハイル',r:'hairu',e:'to enter',c:'Verbs II'},

  // ── Verbs III — Expressive & Game (10) ──
  {jp:'しる',h:'しる',t:'シル',r:'shiru',e:'to know / to find out',c:'Verbs III'},
  {jp:'できる',h:'できる',t:'デキル',r:'dekiru',e:'to be able to / can',c:'Verbs III'},
  {jp:'もらう',h:'もらう',t:'モラウ',r:'morau',e:'to receive',c:'Verbs III'},
  {jp:'あげる',h:'あげる',t:'アゲル',r:'ageru',e:'to give',c:'Verbs III'},
  {jp:'もつ',h:'もつ',t:'モツ',r:'motsu',e:'to hold / to have',c:'Verbs III'},
  {jp:'だす',h:'だす',t:'ダス',r:'dasu',e:'to take out / to submit',c:'Verbs III'},
  {jp:'きめる',h:'きめる',t:'キメル',r:'kimeru',e:'to decide',c:'Verbs III'},
  {jp:'かんがえる',h:'かんがえる',t:'カンガエル',r:'kangaeru',e:'to consider / to ponder',c:'Verbs III'},
  {jp:'えらぶ',h:'えらぶ',t:'エラブ',r:'erabu',e:'to choose / to select',c:'Verbs III'},
  {jp:'かつ',h:'かつ',t:'カツ',r:'katsu',e:'to win',c:'Verbs III'},

  // ── Verbs IV — Combat & Story (10) ──
  {jp:'たたかう',h:'たたかう',t:'タタカウ',r:'tatakau',e:'to fight / to battle',c:'Verbs IV'},
  {jp:'まもる',h:'まもる',t:'マモル',r:'mamoru',e:'to protect / to defend',c:'Verbs IV'},
  {jp:'たすける',h:'たすける',t:'タスケル',r:'tasukeru',e:'to save / to help',c:'Verbs IV'},
  {jp:'にげる',h:'にげる',t:'ニゲル',r:'nigeru',e:'to escape / to flee',c:'Verbs IV'},
  {jp:'せめる',h:'せめる',t:'セメル',r:'semeru',e:'to attack / to assault',c:'Verbs IV'},
  {jp:'まける',h:'まける',t:'マケル',r:'makeru',e:'to lose / to be defeated',c:'Verbs IV'},
  {jp:'しぬ',h:'しぬ',t:'シヌ',r:'shinu',e:'to die',c:'Verbs IV'},
  {jp:'いきる',h:'いきる',t:'イキル',r:'ikiru',e:'to live',c:'Verbs IV'},
  {jp:'めざめる',h:'めざめる',t:'メザメル',r:'mezameru',e:'to awaken / to open one\'s eyes',c:'Verbs IV'},
  {jp:'ちかう',h:'ちかう',t:'チカウ',r:'chikau',e:'to swear / to vow',c:'Verbs IV'},

  // ── Adjectives I — Size, Speed, Quality (10) ──
  {jp:'おおきい',h:'おおきい',t:'オオキイ',r:'ookii',e:'big / large',c:'Adjectives I'},
  {jp:'ちいさい',h:'ちいさい',t:'チイサイ',r:'chiisai',e:'small',c:'Adjectives I'},
  {jp:'たかい',h:'たかい',t:'タカイ',r:'takai',e:'tall / high / expensive',c:'Adjectives I'},
  {jp:'ひくい',h:'ひくい',t:'ヒクイ',r:'hikui',e:'low / short',c:'Adjectives I'},
  {jp:'はやい',h:'はやい',t:'ハヤイ',r:'hayai',e:'fast / early',c:'Adjectives I'},
  {jp:'おそい',h:'おそい',t:'オソイ',r:'osoi',e:'slow / late',c:'Adjectives I'},
  {jp:'あたらしい',h:'あたらしい',t:'アタラシイ',r:'atarashii',e:'new',c:'Adjectives I'},
  {jp:'ふるい',h:'ふるい',t:'フルイ',r:'furui',e:'old (things)',c:'Adjectives I'},
  {jp:'つよい',h:'つよい',t:'ツヨイ',r:'tsuyoi',e:'strong',c:'Adjectives I'},
  {jp:'よわい',h:'よわい',t:'ヨワイ',r:'yowai',e:'weak',c:'Adjectives I'},

  // ── Adjectives II — Feeling & Appearance (10) ──
  {jp:'たのしい',h:'たのしい',t:'タノシイ',r:'tanoshii',e:'fun / enjoyable',c:'Adjectives II'},
  {jp:'かなしい',h:'かなしい',t:'カナシイ',r:'kanashii',e:'sad',c:'Adjectives II'},
  {jp:'こわい',h:'こわい',t:'コワイ',r:'kowai',e:'scary / frightening',c:'Adjectives II'},
  {jp:'きれい',h:'きれい',t:'キレイ',r:'kirei',e:'beautiful / clean',c:'Adjectives II'},
  {jp:'かわいい',h:'かわいい',t:'カワイイ',r:'kawaii',e:'cute / adorable',c:'Adjectives II'},
  {jp:'かっこいい',h:'かっこいい',t:'カッコイイ',r:'kakkoii',e:'cool / stylish',c:'Adjectives II'},
  {jp:'むずかしい',h:'むずかしい',t:'ムズカシイ',r:'muzukashii',e:'difficult',c:'Adjectives II'},
  {jp:'やさしい',h:'やさしい',t:'ヤサシイ',r:'yasashii',e:'kind / gentle / easy',c:'Adjectives II'},
  {jp:'あぶない',h:'あぶない',t:'アブナイ',r:'abunai',e:'dangerous',c:'Adjectives II'},
  {jp:'すごい',h:'すごい',t:'スゴイ',r:'sugoi',e:'amazing / incredible',c:'Adjectives II'},

  // ── Time & Place (10) ──
  {jp:'いま',h:'いま',t:'イマ',r:'ima',e:'now',c:'Time & Place'},
  {jp:'きょう',h:'きょう',t:'キョウ',r:'kyou',e:'today',c:'Time & Place'},
  {jp:'きのう',h:'きのう',t:'キノウ',r:'kinou',e:'yesterday',c:'Time & Place'},
  {jp:'あした',h:'あした',t:'アシタ',r:'ashita',e:'tomorrow',c:'Time & Place'},
  {jp:'まいにち',h:'まいにち',t:'マイニチ',r:'mainichi',e:'every day',c:'Time & Place'},
  {jp:'ここ',h:'ここ',t:'ココ',r:'koko',e:'here',c:'Time & Place'},
  {jp:'そこ',h:'そこ',t:'ソコ',r:'soko',e:'there',c:'Time & Place'},
  {jp:'どこ',h:'どこ',t:'ドコ',r:'doko',e:'where',c:'Time & Place'},
  {jp:'うえ',h:'うえ',t:'ウエ',r:'ue',e:'above / on top',c:'Time & Place'},
  {jp:'した',h:'した',t:'シタ',r:'shita',e:'below / under',c:'Time & Place'},

  // ── Questions (10) ──
  {jp:'なに',h:'なに',t:'ナニ',r:'nani',e:'what',c:'Questions'},
  {jp:'だれ',h:'だれ',t:'ダレ',r:'dare',e:'who',c:'Questions'},
  {jp:'どれ',h:'どれ',t:'ドレ',r:'dore',e:'which one',c:'Questions'},
  {jp:'なぜ',h:'なぜ',t:'ナゼ',r:'naze',e:'why',c:'Questions'},
  {jp:'どうして',h:'どうして',t:'ドウシテ',r:'doushite',e:'why / how come',c:'Questions'},
  {jp:'どのくらい',h:'どのくらい',t:'ドノクライ',r:'dono kurai',e:'how much / how long',c:'Questions'},
  {jp:'いくら',h:'いくら',t:'イクラ',r:'ikura',e:'how much (price)',c:'Questions'},
  {jp:'いつ',h:'いつ',t:'イツ',r:'itsu',e:'when',c:'Questions'},
  {jp:'どう',h:'どう',t:'ドウ',r:'dou',e:'how',c:'Questions'},
  {jp:'なんで',h:'なんで',t:'ナンデ',r:'nande',e:'why / with what',c:'Questions'},

  // ── Emotions (10) ──
  {jp:'うれしい',h:'うれしい',t:'ウレシイ',r:'ureshii',e:'happy / glad',c:'Emotions'},
  {jp:'かなしむ',h:'かなしむ',t:'カナシム',r:'kanashimu',e:'to feel sad / to grieve',c:'Emotions'},
  {jp:'おこる',h:'おこる',t:'オコル',r:'okoru',e:'to get angry',c:'Emotions'},
  {jp:'おそれる',h:'おそれる',t:'オソレル',r:'osoreru',e:'to fear / to be afraid',c:'Emotions'},
  {jp:'なみだ',h:'なみだ',t:'ナミダ',r:'namida',e:'tears',c:'Emotions'},
  {jp:'わらう',h:'わらう',t:'ワラウ',r:'warau',e:'to laugh / to smile',c:'Emotions'},
  {jp:'おどろく',h:'おどろく',t:'オドロク',r:'odoroku',e:'to be surprised',c:'Emotions'},
  {jp:'しんぱい',h:'しんぱい',t:'シンパイ',r:'shinpai',e:'worry / anxiety',c:'Emotions'},
  {jp:'あんしん',h:'あんしん',t:'アンシン',r:'anshin',e:'relief / peace of mind',c:'Emotions'},
  {jp:'こうふん',h:'こうふん',t:'コウフン',r:'koufun',e:'excitement',c:'Emotions'},

  // ── Nature & Weather (10) ──
  {jp:'てんき',h:'てんき',t:'テンキ',r:'tenki',e:'weather',c:'Nature'},
  {jp:'はれ',h:'はれ',t:'ハレ',r:'hare',e:'sunny / clear weather',c:'Nature'},
  {jp:'くもり',h:'くもり',t:'クモリ',r:'kumori',e:'cloudy',c:'Nature'},
  {jp:'あめ',h:'あめ',t:'アメ',r:'ame',e:'rain',c:'Nature'},
  {jp:'かぜ',h:'かぜ',t:'カゼ',r:'kaze',e:'wind',c:'Nature'},
  {jp:'ゆき',h:'ゆき',t:'ユキ',r:'yuki',e:'snow',c:'Nature'},
  {jp:'そら',h:'そら',t:'ソラ',r:'sora',e:'sky',c:'Nature'},
  {jp:'うみ',h:'うみ',t:'ウミ',r:'umi',e:'sea / ocean',c:'Nature'},
  {jp:'やま',h:'やま',t:'ヤマ',r:'yama',e:'mountain',c:'Nature'},
  {jp:'かわ',h:'かわ',t:'カワ',r:'kawa',e:'river',c:'Nature'},

  // ── Food & Drink (10) ──
  {jp:'ごはん',h:'ごはん',t:'ゴハン',r:'gohan',e:'rice / meal',c:'Food & Drink'},
  {jp:'みず',h:'みず',t:'ミズ',r:'mizu',e:'water',c:'Food & Drink'},
  {jp:'おちゃ',h:'おちゃ',t:'オチャ',r:'ocha',e:'tea / green tea',c:'Food & Drink'},
  {jp:'さかな',h:'さかな',t:'サカナ',r:'sakana',e:'fish',c:'Food & Drink'},
  {jp:'にく',h:'にく',t:'ニク',r:'niku',e:'meat',c:'Food & Drink'},
  {jp:'やさい',h:'やさい',t:'ヤサイ',r:'yasai',e:'vegetables',c:'Food & Drink'},
  {jp:'くだもの',h:'くだもの',t:'クダモノ',r:'kudamono',e:'fruit',c:'Food & Drink'},
  {jp:'パン',h:'ぱん',t:'パン',r:'pan',e:'bread',c:'Food & Drink'},
  {jp:'ラーメン',h:'らーめん',t:'ラーメン',r:'raamen',e:'ramen noodles',c:'Food & Drink'},
  {jp:'すし',h:'すし',t:'スシ',r:'sushi',e:'sushi',c:'Food & Drink'},

  // ── Body & Health (10) ──
  {jp:'からだ',h:'からだ',t:'カラダ',r:'karada',e:'body',c:'Body & Health'},
  {jp:'あたま',h:'あたま',t:'アタマ',r:'atama',e:'head',c:'Body & Health'},
  {jp:'て',h:'て',t:'テ',r:'te',e:'hand',c:'Body & Health'},
  {jp:'あし',h:'あし',t:'アシ',r:'ashi',e:'foot / leg',c:'Body & Health'},
  {jp:'め',h:'め',t:'メ',r:'me',e:'eye',c:'Body & Health'},
  {jp:'みみ',h:'みみ',t:'ミミ',r:'mimi',e:'ear',c:'Body & Health'},
  {jp:'くち',h:'くち',t:'クチ',r:'kuchi',e:'mouth',c:'Body & Health'},
  {jp:'こころ',h:'こころ',t:'ココロ',r:'kokoro',e:'heart / mind',c:'Body & Health'},
  {jp:'いたい',h:'いたい',t:'イタイ',r:'itai',e:'painful / it hurts',c:'Body & Health'},
  {jp:'げんき',h:'げんき',t:'ゲンキ',r:'genki',e:'healthy / energetic / fine',c:'Body & Health'},

  // ── Numbers & Counters (10) ──
  {jp:'ひとつ',h:'ひとつ',t:'ヒトツ',r:'hitotsu',e:'one (native counting)',c:'Numbers'},
  {jp:'ふたつ',h:'ふたつ',t:'フタツ',r:'futatsu',e:'two (native counting)',c:'Numbers'},
  {jp:'みっつ',h:'みっつ',t:'ミッツ',r:'mittsu',e:'three (native counting)',c:'Numbers'},
  {jp:'よっつ',h:'よっつ',t:'ヨッツ',r:'yottsu',e:'four (native counting)',c:'Numbers'},
  {jp:'いつつ',h:'いつつ',t:'イツツ',r:'itsutsu',e:'five (native counting)',c:'Numbers'},
  {jp:'たくさん',h:'たくさん',t:'タクサン',r:'takusan',e:'many / a lot',c:'Numbers'},
  {jp:'すこし',h:'すこし',t:'スコシ',r:'sukoshi',e:'a little / a few',c:'Numbers'},
  {jp:'ぜんぶ',h:'ぜんぶ',t:'ゼンブ',r:'zenbu',e:'all / everything',c:'Numbers'},
  {jp:'なんにん',h:'なんにん',t:'ナンニン',r:'nannin',e:'how many people',c:'Numbers'},
  {jp:'いちばん',h:'いちばん',t:'イチバン',r:'ichiban',e:'number one / the most / the best',c:'Numbers'},

  // ── Home & Daily Life (10) ──
  {jp:'いえ',h:'いえ',t:'イエ',r:'ie',e:'house / home',c:'Daily Life'},
  {jp:'へや',h:'へや',t:'ヘヤ',r:'heya',e:'room',c:'Daily Life'},
  {jp:'まど',h:'まど',t:'マド',r:'mado',e:'window',c:'Daily Life'},
  {jp:'ドア',h:'どあ',t:'ドア',r:'doa',e:'door',c:'Daily Life'},
  {jp:'つくえ',h:'つくえ',t:'ツクエ',r:'tsukue',e:'desk',c:'Daily Life'},
  {jp:'いす',h:'いす',t:'イス',r:'isu',e:'chair',c:'Daily Life'},
  {jp:'ほん',h:'ほん',t:'ホン',r:'hon',e:'book',c:'Daily Life'},
  {jp:'かみ',h:'かみ',t:'カミ',r:'kami',e:'paper',c:'Daily Life'},
  {jp:'でんわ',h:'でんわ',t:'デンワ',r:'denwa',e:'telephone',c:'Daily Life'},
  {jp:'おかね',h:'おかね',t:'オカネ',r:'okane',e:'money',c:'Daily Life'},

  // ── Transport & City (10) ──
  {jp:'でんしゃ',h:'でんしゃ',t:'デンシャ',r:'densha',e:'train',c:'Transport'},
  {jp:'バス',h:'ばす',t:'バス',r:'basu',e:'bus',c:'Transport'},
  {jp:'くるま',h:'くるま',t:'クルマ',r:'kuruma',e:'car',c:'Transport'},
  {jp:'えき',h:'えき',t:'エキ',r:'eki',e:'train station',c:'Transport'},
  {jp:'みち',h:'みち',t:'ミチ',r:'michi',e:'road / way / path',c:'Transport'},
  {jp:'みせ',h:'みせ',t:'ミセ',r:'mise',e:'shop / store',c:'Transport'},
  {jp:'びょういん',h:'びょういん',t:'ビョウイン',r:'byouin',e:'hospital',c:'Transport'},
  {jp:'がっこう',h:'がっこう',t:'ガッコウ',r:'gakkou',e:'school',c:'Transport'},
  {jp:'こうえん',h:'こうえん',t:'コウエン',r:'kouen',e:'park',c:'Transport'},
  {jp:'ひだり',h:'ひだり',t:'ヒダリ',r:'hidari',e:'left',c:'Transport'},
  {jp:'みぎ',h:'みぎ',t:'ミギ',r:'migi',e:'right',c:'Transport'},

  // ── Game & VN I — Combat (10) ──
  {jp:'たたかい',h:'たたかい',t:'タタカイ',r:'tatakai',e:'battle / fight',c:'Game & VN I'},
  {jp:'まほう',h:'まほう',t:'マホウ',r:'mahou',e:'magic / spell',c:'Game & VN I'},
  {jp:'ゆうしゃ',h:'ゆうしゃ',t:'ユウシャ',r:'yuusha',e:'hero / brave warrior',c:'Game & VN I'},
  {jp:'まおう',h:'まおう',t:'マオウ',r:'maou',e:'demon king',c:'Game & VN I'},
  {jp:'つるぎ',h:'つるぎ',t:'ツルギ',r:'tsurugi',e:'sword (classic/poetic)',c:'Game & VN I'},
  {jp:'よろい',h:'よろい',t:'ヨロイ',r:'yoroi',e:'armour',c:'Game & VN I'},
  {jp:'たて',h:'たて',t:'タテ',r:'tate',e:'shield',c:'Game & VN I'},
  {jp:'ちから',h:'ちから',t:'チカラ',r:'chikara',e:'power / strength',c:'Game & VN I'},
  {jp:'なかま',h:'なかま',t:'ナカマ',r:'nakama',e:'companion / comrade',c:'Game & VN I'},
  {jp:'てき',h:'てき',t:'テキ',r:'teki',e:'enemy',c:'Game & VN I'},

  // ── Game & VN II — Story & Fate (10) ──
  {jp:'いのち',h:'いのち',t:'イノチ',r:'inochi',e:'life / one\'s life',c:'Game & VN II'},
  {jp:'たましい',h:'たましい',t:'タマシイ',r:'tamashii',e:'soul / spirit',c:'Game & VN II'},
  {jp:'うんめい',h:'うんめい',t:'ウンメイ',r:'unmei',e:'fate / destiny',c:'Game & VN II'},
  {jp:'ゆめ',h:'ゆめ',t:'ユメ',r:'yume',e:'dream',c:'Game & VN II'},
  {jp:'きぼう',h:'きぼう',t:'キボウ',r:'kibou',e:'hope',c:'Game & VN II'},
  {jp:'ぜつぼう',h:'ぜつぼう',t:'ゼツボウ',r:'zetsubou',e:'despair',c:'Game & VN II'},
  {jp:'あい',h:'あい',t:'アイ',r:'ai',e:'love',c:'Game & VN II'},
  {jp:'きずな',h:'きずな',t:'キズナ',r:'kizuna',e:'bond / emotional tie',c:'Game & VN II'},
  {jp:'ひみつ',h:'ひみつ',t:'ヒミツ',r:'himitsu',e:'secret',c:'Game & VN II'},
  {jp:'しんじつ',h:'しんじつ',t:'シンジツ',r:'shinjitsu',e:'truth',c:'Game & VN II'},

  // ── Game & VN III — World & Systems (10) ──
  {jp:'おうじょ',h:'おうじょ',t:'オウジョ',r:'oujo',e:'princess',c:'Game & VN III'},
  {jp:'おうさま',h:'おうさま',t:'オウサマ',r:'ousama',e:'king',c:'Game & VN III'},
  {jp:'しろ',h:'しろ',t:'シロ',r:'shiro',e:'castle',c:'Game & VN III'},
  {jp:'ダンジョン',h:'だんじょん',t:'ダンジョン',r:'danjon',e:'dungeon',c:'Game & VN III'},
  {jp:'レベル',h:'れべる',t:'レベル',r:'reberu',e:'level',c:'Game & VN III'},
  {jp:'けいけん',h:'けいけん',t:'ケイケン',r:'keiken',e:'experience',c:'Game & VN III'},
  {jp:'クエスト',h:'くえすと',t:'クエスト',r:'kuesuto',e:'quest',c:'Game & VN III'},
  {jp:'ボス',h:'ぼす',t:'ボス',r:'bosu',e:'boss',c:'Game & VN III'},
  {jp:'アイテム',h:'あいてむ',t:'アイテム',r:'aitemu',e:'item',c:'Game & VN III'},
  {jp:'やみ',h:'やみ',t:'ヤミ',r:'yami',e:'darkness',c:'Game & VN III'},

  // ── World & Settings (10) ──
  {jp:'まち',h:'まち',t:'マチ',r:'machi',e:'town / city',c:'World'},
  {jp:'むら',h:'むら',t:'ムラ',r:'mura',e:'village',c:'World'},
  {jp:'もり',h:'もり',t:'モリ',r:'mori',e:'forest',c:'World'},
  {jp:'さばく',h:'さばく',t:'サバク',r:'sabaku',e:'desert',c:'World'},
  {jp:'どうくつ',h:'どうくつ',t:'ドウクツ',r:'doukutsu',e:'cave / cavern',c:'World'},
  {jp:'とう',h:'とう',t:'トウ',r:'tou',e:'tower',c:'World'},
  {jp:'しま',h:'しま',t:'シマ',r:'shima',e:'island',c:'World'},
  {jp:'おうこく',h:'おうこく',t:'オウコク',r:'oukoku',e:'kingdom',c:'World'},
  {jp:'へいや',h:'へいや',t:'ヘイヤ',r:'heiya',e:'plain / open field',c:'World'},
  {jp:'みなと',h:'みなと',t:'ミナト',r:'minato',e:'harbour / port',c:'World'},
// ── School & Study (10) ──
  {jp:'べんきょう',h:'べんきょう',t:'ベンキョウ',r:'benkyou',e:'study',c:'School'},
  {jp:'じゅぎょう',h:'じゅぎょう',t:'ジュギョウ',r:'jugyou',e:'class / lesson',c:'School'},
  {jp:'しゅくだい',h:'しゅくだい',t:'シュクダイ',r:'shukudai',e:'homework',c:'School'},
  {jp:'しけん',h:'しけん',t:'シケン',r:'shiken',e:'exam / test',c:'School'},
  {jp:'きょうしつ',h:'きょうしつ',t:'キョウシツ',r:'kyoushitsu',e:'classroom',c:'School'},
  {jp:'せいふく',h:'せいふく',t:'セイフク',r:'seifuku',e:'school uniform',c:'School'},
  {jp:'ぶかつ',h:'ぶかつ',t:'ブカツ',r:'bukatsu',e:'club activities',c:'School'},
  {jp:'にほんご',h:'にほんご',t:'ニホンゴ',r:'nihongo',e:'Japanese language',c:'School'},
  {jp:'おんがく',h:'おんがく',t:'オンガク',r:'ongaku',e:'music',c:'School'},
  {jp:'としょかん',h:'としょかん',t:'トショカン',r:'toshokan',e:'library',c:'School'},

  // ── Family (10) ──
  {jp:'おとうさん',h:'おとうさん',t:'オトウサン',r:'otousan',e:'father (polite)',c:'Family'},
  {jp:'おかあさん',h:'おかあさん',t:'オカアサン',r:'okaasan',e:'mother (polite)',c:'Family'},
  {jp:'おにいさん',h:'おにいさん',t:'オニイサン',r:'oniisan',e:'older brother (polite)',c:'Family'},
  {jp:'おねえさん',h:'おねえさん',t:'オネエサン',r:'oneesan',e:'older sister (polite)',c:'Family'},
  {jp:'おとうと',h:'おとうと',t:'オトウト',r:'otouto',e:'younger brother',c:'Family'},
  {jp:'いもうと',h:'いもうと',t:'イモウト',r:'imouto',e:'younger sister',c:'Family'},
  {jp:'おじいさん',h:'おじいさん',t:'オジイサン',r:'ojiisan',e:'grandfather / old man',c:'Family'},
  {jp:'おばあさん',h:'おばあさん',t:'オバアサン',r:'obaasan',e:'grandmother / old woman',c:'Family'},
  {jp:'かぞく',h:'かぞく',t:'カゾク',r:'kazoku',e:'family',c:'Family'},
  {jp:'きょうだい',h:'きょうだい',t:'キョウダイ',r:'kyoudai',e:'siblings / brothers and sisters',c:'Family'},

  // ── Colours (10) ──
  {jp:'あか',h:'あか',t:'アカ',r:'aka',e:'red',c:'Colours'},
  {jp:'あお',h:'あお',t:'アオ',r:'ao',e:'blue / green',c:'Colours'},
  {jp:'きいろ',h:'きいろ',t:'キイロ',r:'kiiro',e:'yellow',c:'Colours'},
  {jp:'みどり',h:'みどり',t:'ミドリ',r:'midori',e:'green',c:'Colours'},
  {jp:'しろい',h:'しろい',t:'シロイ',r:'shiroi',e:'white',c:'Colours'},
  {jp:'くろ',h:'くろ',t:'クロ',r:'kuro',e:'black',c:'Colours'},
  {jp:'ちゃいろ',h:'ちゃいろ',t:'チャイロ',r:'chairo',e:'brown',c:'Colours'},
  {jp:'むらさき',h:'むらさき',t:'ムラサキ',r:'murasaki',e:'purple',c:'Colours'},
  {jp:'オレンジ',h:'おれんじ',t:'オレンジ',r:'orenji',e:'orange',c:'Colours'},
  {jp:'ピンク',h:'ぴんく',t:'ピンク',r:'pinku',e:'pink',c:'Colours'},

  // ── Verbs V — Everyday (10) ──
  {jp:'あそぶ',h:'あそぶ',t:'アソブ',r:'asobu',e:'to play / to have fun',c:'Verbs V'},
  {jp:'はたらく',h:'はたらく',t:'ハタラク',r:'hataraku',e:'to work',c:'Verbs V'},
  {jp:'やすむ',h:'やすむ',t:'ヤスム',r:'yasumu',e:'to rest / to take a break',c:'Verbs V'},
  {jp:'よぶ',h:'よぶ',t:'ヨブ',r:'yobu',e:'to call / to invite / to summon',c:'Verbs V'},
  {jp:'なる',h:'なる',t:'ナル',r:'naru',e:'to become',c:'Verbs V'},
  {jp:'いる',h:'いる',t:'イル',r:'iru',e:'to exist (animate)',c:'Verbs V'},
  {jp:'ある',h:'ある',t:'アル',r:'aru',e:'to exist (inanimate)',c:'Verbs V'},
  {jp:'うごく',h:'うごく',t:'ウゴク',r:'ugoku',e:'to move',c:'Verbs V'},
  {jp:'とまる',h:'とまる',t:'トマル',r:'tomaru',e:'to stop / to come to a halt',c:'Verbs V'},
  {jp:'かわる',h:'かわる',t:'カワル',r:'kawaru',e:'to change / to transform',c:'Verbs V'},

  // ── Game & VN IV — Isekai & Fantasy (10) ──
  {jp:'てんせい',h:'てんせい',t:'テンセイ',r:'tensei',e:'reincarnation / transmigration',c:'Game & VN IV'},
  {jp:'いせかい',h:'いせかい',t:'イセカイ',r:'isekai',e:'another world / different world',c:'Game & VN IV'},
  {jp:'まりょく',h:'まりょく',t:'マリョク',r:'maryoku',e:'magic power / MP',c:'Game & VN IV'},
  {jp:'ぼうけん',h:'ぼうけん',t:'ボウケン',r:'bouken',e:'adventure',c:'Game & VN IV'},
  {jp:'でんせつ',h:'でんせつ',t:'デンセツ',r:'densetsu',e:'legend / legendary',c:'Game & VN IV'},
  {jp:'ひっさつ',h:'ひっさつ',t:'ヒッサツ',r:'hissatsu',e:'sure kill / finishing move',c:'Game & VN IV'},
  {jp:'むてき',h:'むてき',t:'ムテキ',r:'muteki',e:'invincible / unbeatable',c:'Game & VN IV'},
  {jp:'さいきょう',h:'さいきょう',t:'サイキョウ',r:'saikyou',e:'the strongest',c:'Game & VN IV'},
  {jp:'さいしゅう',h:'さいしゅう',t:'サイシュウ',r:'saishuu',e:'final / last',c:'Game & VN IV'},
  {jp:'えいゆう',h:'えいゆう',t:'エイユウ',r:'eiyuu',e:'hero / great warrior',c:'Game & VN IV'},

  // ── VN Adjectives (10) ──
  {jp:'つらい',h:'つらい',t:'ツライ',r:'tsurai',e:'painful / hard / tough',c:'VN Adjectives'},
  {jp:'はずかしい',h:'はずかしい',t:'ハズカシイ',r:'hazukashii',e:'embarrassing / shy',c:'VN Adjectives'},
  {jp:'なつかしい',h:'なつかしい',t:'ナツカシイ',r:'natsukashii',e:'nostalgic / fondly missed',c:'VN Adjectives'},
  {jp:'さみしい',h:'さみしい',t:'サミシイ',r:'samishii',e:'lonely',c:'VN Adjectives'},
  {jp:'うらやましい',h:'うらやましい',t:'ウラヤマシイ',r:'urayamashii',e:'envious / jealous',c:'VN Adjectives'},
  {jp:'たいせつ',h:'たいせつ',t:'タイセツ',r:'taisetsu',e:'important / precious / dear',c:'VN Adjectives'},
  {jp:'ふしぎ',h:'ふしぎ',t:'フシギ',r:'fushigi',e:'mysterious / strange / wonder',c:'VN Adjectives'},
  {jp:'せつない',h:'せつない',t:'セツナイ',r:'setsunai',e:'heartbreaking / bittersweet',c:'VN Adjectives'},
  {jp:'もったいない',h:'もったいない',t:'モッタイナイ',r:'mottainai',e:'wasteful / what a waste',c:'VN Adjectives'},
  {jp:'しかたない',h:'しかたない',t:'シカタナイ',r:'shikatanai',e:'can\'t be helped / no choice',c:'VN Adjectives'},

  // ── RPG Systems (10) ──
  {jp:'パーティー',h:'ぱーてぃー',t:'パーティー',r:'paatii',e:'party / group',c:'RPG Systems'},
  {jp:'ギルド',h:'ぎるど',t:'ギルド',r:'girudo',e:'guild',c:'RPG Systems'},
  {jp:'みかた',h:'みかた',t:'ミカタ',r:'mikata',e:'ally / one\'s side',c:'RPG Systems'},
  {jp:'せんし',h:'せんし',t:'センシ',r:'senshi',e:'warrior / fighter',c:'RPG Systems'},
  {jp:'まほうつかい',h:'まほうつかい',t:'マホウツカイ',r:'mahoutsukai',e:'mage / wizard',c:'RPG Systems'},
  {jp:'とうぞく',h:'とうぞく',t:'トウゾク',r:'touzoku',e:'thief / rogue',c:'RPG Systems'},
  {jp:'どうぐ',h:'どうぐ',t:'ドウグ',r:'dougu',e:'tool / equipment / item',c:'RPG Systems'},
  {jp:'ほうび',h:'ほうび',t:'ホウビ',r:'houbi',e:'reward / prize',c:'RPG Systems'},
  {jp:'スキル',h:'すきる',t:'スキル',r:'sukiru',e:'skill (game ability)',c:'RPG Systems'},
  {jp:'ステータス',h:'すてーたす',t:'ステータス',r:'suteetasu',e:'status / stats',c:'RPG Systems'},
];
  
